# Generated by Django 4.2.25 on 2025-10-03 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=16)),
                ('status', models.CharField(default='PENDING', max_length=32)),
                ('target_lang', models.CharField(default='hi', max_length=32)),
                ('input_path', models.FilePathField(blank=True, max_length=512)),
                ('transcript_text', models.TextField(blank=True)),
                ('translation_text', models.TextField(blank=True)),
                ('srt_path', models.FilePathField(blank=True, max_length=512)),
                ('vtt_path', models.FilePathField(blank=True, max_length=512)),
                ('dubbed_audio_path', models.FilePathField(blank=True, max_length=512)),
                ('dubbed_video_path', models.FilePathField(blank=True, max_length=512)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
